#define VOID    1
#define VAR     2
#define IF      3
#define ELSE    4
#define WHILE   5
#define PRINT   6
#define READ    7
#define ID      8
#define ENTERO  9
#define STRING  10
#define PC      11
#define COMA    12
#define MAS     13
#define MENOS   14
#define POR     15
#define DIV     16
#define IGUAL   17
#define PARI    18
#define PARD    19
#define LLAVEI  20
#define LLAVED  21
#define CONST   22
#define DO      23
#define MENOR   24
#define MAYOR   25
#define EXCLAM  26
#define FOR     27